### ISSUE TITLE
support type-changing lenses

### ISSUE THREAD

**Issue by aavogt** [VinylRecords/Vinyl#20]
Only `Lens'` are provided in Data.Vinyl.Lens. Less restrictive ones should be possible.

**Comment by heptahedron** [comment]
I actually encountered this when I was working on `vinyl-json` and I have what appears to be a working solution in https://github.com/heptahedron/vinyl-json/blob/master/src/Data/Vinyl/Json/Lens.hs . I could make a pull request here if you thought this implementation looked fine?

**Comment by acowley** [comment]
Thanks for reviving this effort! How have you found the usability of this? Any issues with inference?

**Comment by heptahedron** [comment]
I don't think so--I had to add `UndecidableInstances`, but it seems to work pretty well. I'm trying to avoid any dependencies on a lens library to keep this package minimal, but for the example `JsonRec TestFields` type [here](https://github.com/heptahedron/vinyl-json/blob/master/src/Data/Vinyl/Json.hs), you can do e.g. `testRec & jrf @"opt_present_bool" . mapped .~ "foo"` just fine, and the contained type goes from `Bool` to `String` as you'd expect, without complaining. I've added extra type annotations to some of the lenses because the parameter to my `JsonField` type is a triple of its name, optionality, and the actual type it contains, but the type inference works even when e.g. changing the name/optionality of a field within a `JsonRec`.
