### ISSUE TITLE
Subset Instance?

### ISSUE THREAD

**Issue by vladfi1** [VinylRecords/Vinyl#70]
I'd like to have something like the following:

    instance (is' ~ ???, RSubset rs ss is) => RSubset rs (s ': ss) is'

Is this possible?

**Comment by andrewthad** [comment]
There are two instances of RSubset in vinyl:

    instance RSubset '[] ss '[]
    instance (RElem r ss i , RSubset rs ss is) => RSubset (r ': rs) ss (i ': is)

I'm not sure what you want your instance to do, and you would probably need OverlappingInstances for it to work. You will need to clarify what you are trying to do.

**Comment by vladfi1** [comment]
I think it's pretty obvious what I'm trying to express: that if rs is a subset of ss, and we add another element s to ss, then rs will be a subset of s ': ss. For implementation, casting should certainly be easy: just take the rtail first. I'm not sure about the other class methods though, or what to do with the index type variable.

**Comment by jonsterling** [comment]
Hi @vladfi1—frustratingly, the weakening judgement `RSubset rs ss _ => RSubset rs (s ': ss)` is admissible, but not derivable by the constraint solver given the current definitions. Also, you cannot add another instance, since the ones given are meant to constitute a syntax-directed algorithm for deciding subsethood.

In the past, when I needed something like this, I was able to get away with using proof terms to demonstrate the validity of the weakening judgement. For instance, you can write a program which derives a subset lens for your use-case, and then use it in place of the automatic resolution provided by the type classes. Specifically, you may write a function of the following type:

```haskell
weaken :: Lens (Rec f ss) (Rec f rs) -> Lens (Rec f (s ': ss)) (Rec f rs)
```

I do not have time today to demonstrate the technique; if my explanation has been sufficient, I am very pleased, but otherwise, feel free to leave this issue open and keep bugging me until I have been able to demonstrate it properly.

**Comment by vladfi1** [comment]
My type-fu has increased to the point where all this makes sense. Sometimes I feel like scrapping all my typeclasses and using singletons instead.
